import type { Affordance } from "./types";

export const AFFORDANCES: Affordance[] = [
  // —— Studio, Griff ——
  {
    id: "studio-tasse",
    locusId: "studio",
    title: "Tasse auf dem Tisch",
    verb: "Trinken",
    description: "Armlänge. Kein Weg, nur greifen.",
    humanUse: "Den Körper im Stehen versorgen, ohne den Raum zu verlassen.",
    dimension: "konsumieren",
    lx: 0.55,
    ly: 0.4,
    visibleStanding: true,
    requiresWalk: false,
    walkSeconds: 2,
    salience: 0.55,
  },
  {
    id: "studio-controller",
    locusId: "studio",
    title: "Controller auf der Kommode",
    verb: "Greifen",
    description: "MIDI-Tastatur in Reichweite, wenn du dich drehst.",
    humanUse: "Sofort in Klang gehen, ohne den Schreibtisch aufzusuchen.",
    dimension: "schaffen",
    lx: 0.95,
    ly: -0.35,
    visibleStanding: true,
    requiresWalk: false,
    walkSeconds: 3,
    salience: 0.8,
  },
  {
    id: "studio-notiz",
    locusId: "studio",
    title: "Notizbuch",
    verb: "Aufschlagen",
    description: "Offene Seite, Stift daneben.",
    humanUse: "Einen Einfall festhalten, bevor er sich verzieht.",
    dimension: "informieren",
    lx: -0.4,
    ly: 0.5,
    visibleStanding: true,
    requiresWalk: false,
    walkSeconds: 2,
    salience: 0.6,
  },

  // —— Studio, Raum (das Beispiel: sehen und hingehen) ——
  {
    id: "studio-licht",
    locusId: "studio",
    title: "Lichtschalter",
    verb: "Betätigen",
    description: "An der Wand neben der Tür. Vom Standpunkt in der Raummitte sichtbar.",
    humanUse: "Helligkeit ändern, ohne den Platz am Rechner einzunehmen.",
    dimension: "handeln",
    lx: 3.35,
    ly: -0.15,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 6,
    salience: 0.97,
    features: ["Wand", "Griffweite am Ziel"],
    umwelt: "mensch",
    wiring: { domain: "haus", adapterId: "haus-mensch" },
  },
  {
    id: "studio-rollo",
    locusId: "studio",
    title: "Rollladen",
    verb: "Hoch- oder runterlassen",
    description: "Am Nordfenster. Du siehst den Gurt, musst aber hinlaufen.",
    humanUse: "Licht, Blick und Nachbarschaft dosieren — typische Raumnutzung im Stehen.",
    dimension: "handeln",
    lx: 0.35,
    ly: 3.85,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 7,
    salience: 0.99,
    features: ["Fenster", "Gurt"],
    umwelt: "mensch",
    wiring: { domain: "haus", adapterId: "haus-mensch" },
  },
  {
    id: "studio-fenster",
    locusId: "studio",
    title: "Fensterflügel",
    verb: "Öffnen / lüften",
    description: "Neben dem Rollladen. Geruch und Luftwechsel.",
    humanUse: "Den Raum atmen lassen, ohne ihn zu verlassen.",
    dimension: "handeln",
    lx: -0.7,
    ly: 3.85,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 7,
    salience: 0.74,
  },
  {
    id: "studio-tuer",
    locusId: "studio",
    title: "Tür zum Flur",
    verb: "Durchgehen",
    description: "Östliche Wand. Schwelle zu den Nachbarräumen.",
    humanUse: "Den Horizont der Wohnung öffnen.",
    dimension: "handeln",
    lx: 3.5,
    ly: 0.75,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 6,
    salience: 0.72,
    travelToLocusId: "flur",
    features: ["Schwelle", "Nachbarräume"],
  },
  {
    id: "studio-gitarre",
    locusId: "studio",
    title: "Gitarre an der Wand",
    verb: "Abnehmen",
    description: "Südwand. Im Rücken, wenn du zum Fenster schaust.",
    humanUse: "Ins Instrument fallen, ohne den Computer aufzuwecken.",
    dimension: "schaffen",
    lx: -0.35,
    ly: -3.15,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 6,
    salience: 0.88,
  },
  {
    id: "studio-regal",
    locusId: "studio",
    title: "Regal mit Vinyl",
    verb: "Ziehen / auflegen",
    description: "Neben der Gitarre. Bestand an Hörbarem.",
    humanUse: "Etwas wählen und den Raum umstimmen.",
    dimension: "schaffen",
    lx: 1.45,
    ly: -3.15,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 7,
    salience: 0.62,
    features: ["Hülle lesen", "Platte auflegen"],
  },
  {
    id: "studio-heizung",
    locusId: "studio",
    title: "Thermostat",
    verb: "Stellen",
    description: "Unter dem Fensterbrett.",
    humanUse: "Temperatur als leibliche Bedingung justieren.",
    dimension: "handeln",
    lx: 1.35,
    ly: 3.7,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 8,
    salience: 0.5,
  },
  {
    id: "studio-stuhl",
    locusId: "studio",
    title: "Stuhl am Fenster",
    verb: "Setzen",
    description: "Nicht der Arbeitsstuhl. Ein Sitz zum Hören.",
    humanUse: "Im Raum bleiben und zur Ruhe kommen.",
    dimension: "ruhen",
    lx: 1.75,
    ly: 2.7,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 5,
    salience: 0.58,
  },
  {
    id: "studio-monitor",
    locusId: "studio",
    title: "Studiomonitore",
    verb: "Ausrichten",
    description: "Auf den Stativen, seitlich im Blick.",
    humanUse: "Den Hörraum kalibrieren, nicht am Rechner sitzen.",
    dimension: "schaffen",
    lx: -2.35,
    ly: 1.15,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 5,
    salience: 0.64,
  },
  {
    id: "studio-computer",
    locusId: "studio",
    title: "Schreibtisch mit Rechner",
    verb: "Hinsetzen",
    description: "Westwand. Im Beispiel bewusst nicht der Standort — hinter oder seitlich.",
    humanUse: "Digitale Arbeit; im Feld absichtlich nachrangig, weil du im Raum stehst.",
    dimension: "schaffen",
    lx: -3.15,
    ly: 0.35,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 6,
    salience: 0.32,
  },
  {
    id: "studio-ausblick",
    locusId: "studio",
    title: "Blick auf die Höfe",
    verb: "Hinaussehen",
    description: "Was das Fenster anbietet, ohne es zu öffnen.",
    humanUse: "Lage prüfen: Wetter, Tageszeit, wer unten geht.",
    dimension: "wahrnehmen",
    lx: 0.15,
    ly: 4.0,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 6,
    salience: 0.7,
  },

  // —— Nachbarräume ——
  {
    id: "flur-verteiler",
    locusId: "flur",
    title: "Wohnungsflur",
    verb: "Betreten",
    description: "Wenige Meter. Von hier aus Küche, Bad, Wohnzimmer.",
    humanUse: "Den nächsten Raum wählen.",
    dimension: "handeln",
    lx: 0,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 8,
    salience: 0.5,
    travelToLocusId: "flur",
  },
  {
    id: "flur-jacke",
    locusId: "flur",
    title: "Garderobe",
    verb: "Jacke nehmen",
    description: "Haken an der Flurwand. Feature der Schwelle nach draußen.",
    humanUse: "Den Körper für den Kiez anziehen.",
    dimension: "handeln",
    lx: 0.1,
    ly: 1.4,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 10,
    salience: 0.46,
    travelToLocusId: "flur",
  },
  {
    id: "kueche-wasser",
    locusId: "kueche",
    title: "Wasserkocher",
    verb: "Aufsetzen",
    description: "Nachbarraum. Du siehst ihn nicht, weißt ihn aber.",
    humanUse: "Trinken und Wärme herstellen.",
    dimension: "konsumieren",
    lx: 0.5,
    ly: 0.4,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 18,
    salience: 0.72,
    travelToLocusId: "kueche",
    features: ["Hahn", "Tasse", "Vorrat"],
  },
  {
    id: "kueche-herd",
    locusId: "kueche",
    title: "Herd",
    verb: "Kochen",
    description: "Essen machen, nicht nur Wasser.",
    humanUse: "Sich oder andere versorgen.",
    dimension: "konsumieren",
    lx: -0.4,
    ly: 1.1,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 20,
    salience: 0.52,
    travelToLocusId: "kueche",
  },
  {
    id: "kueche-kuehl",
    locusId: "kueche",
    title: "Kühlschrank",
    verb: "Öffnen",
    description: "Bestand der Wohnung: Reste, Milch, was noch da ist.",
    humanUse: "Nachsehen, bevor man zur Bäckerei geht.",
    dimension: "konsumieren",
    lx: 1.8,
    ly: -0.6,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 20,
    salience: 0.64,
    travelToLocusId: "kueche",
    inventory: [
      { name: "Milch", available: ["morgen", "tag", "abend"] },
      { name: "Butter", available: ["morgen", "tag", "abend", "nacht"] },
      { name: "Reste von gestern", available: ["morgen", "tag"], note: "abends unsicher" },
    ],
  },
  {
    id: "kueche-kaffee",
    locusId: "kueche",
    title: "Siebträger",
    verb: "Beziehen",
    description: "Morgens das zweite sinnvolle Feature der Küche.",
    humanUse: "Wach werden, ohne das Studio zu verlassen.",
    dimension: "konsumieren",
    lx: 0.2,
    ly: 1.4,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 18,
    salience: 0.6,
    travelToLocusId: "kueche",
    closedAt: ["nacht"],
  },
  {
    id: "kueche-blick",
    locusId: "kueche",
    title: "Küchenfenster",
    verb: "Hinaussehen",
    description: "Hofseite, anderer Ausschnitt als im Studio.",
    humanUse: "Wetter prüfen, während Wasser kocht.",
    dimension: "wahrnehmen",
    lx: 1.4,
    ly: -2.6,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 22,
    salience: 0.36,
    travelToLocusId: "kueche",
  },
  {
    id: "bad-waschen",
    locusId: "bad",
    title: "Waschbecken",
    verb: "Hände waschen",
    description: "Kurzer Weg, geschlossene Tür.",
    humanUse: "Körperliche Schwelle zwischen Arbeit und Rest.",
    dimension: "ruhen",
    lx: 0.2,
    ly: 0.5,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 16,
    salience: 0.6,
    travelToLocusId: "bad",
  },
  {
    id: "bad-dusche",
    locusId: "bad",
    title: "Dusche",
    verb: "Duschen",
    description: "Der eigentliche Care-Kern des Bades.",
    humanUse: "Den Arbeitstag vom Körper nehmen.",
    dimension: "ruhen",
    lx: -1.2,
    ly: -1.2,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 18,
    salience: 0.48,
    travelToLocusId: "bad",
  },
  {
    id: "bad-spiegel",
    locusId: "bad",
    title: "Spiegelschrank",
    verb: "Nachsehen",
    description: "Gesicht, Medikamente, was noch da ist.",
    humanUse: "Kurze Selbstvergewisserung, kein Aufenthalt.",
    dimension: "informieren",
    lx: 0.3,
    ly: 0.9,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 16,
    salience: 0.38,
    travelToLocusId: "bad",
  },
  {
    id: "wohn-sofa",
    locusId: "wohnzimmer",
    title: "Sofa",
    verb: "Legen / sitzen",
    description: "Der andere Innenraum. Nicht arbeiten.",
    humanUse: "Aus dem Studio austreten, ohne die Wohnung zu verlassen.",
    dimension: "ruhen",
    lx: -0.4,
    ly: -0.6,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 14,
    salience: 0.7,
    travelToLocusId: "wohnzimmer",
  },
  {
    id: "wohn-fenster",
    locusId: "wohnzimmer",
    title: "Straßenfenster",
    verb: "Hinaussehen",
    description: "Wer kommt, welches Licht die Venloer hat.",
    humanUse: "Die Wohnung an den Kiez koppeln.",
    dimension: "wahrnehmen",
    lx: 0.4,
    ly: 2.6,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 16,
    salience: 0.46,
    travelToLocusId: "wohnzimmer",
  },
  {
    id: "wohn-lampe",
    locusId: "wohnzimmer",
    title: "Stehlampe",
    verb: "Schalten",
    description: "Abendlicht, nicht die Decke des Studios.",
    humanUse: "Den sozialen Raum stimmungsmäßig öffnen.",
    dimension: "handeln",
    lx: 1.6,
    ly: 1.2,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 15,
    salience: 0.42,
    travelToLocusId: "wohnzimmer",
  },
  {
    id: "wohn-regal",
    locusId: "wohnzimmer",
    title: "Bücherregal",
    verb: "Ziehen / lesen",
    description: "Bestand an Text, nicht an Klang.",
    humanUse: "Etwas wählen und sich setzen.",
    dimension: "informieren",
    lx: 2.0,
    ly: -1.8,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 16,
    salience: 0.4,
    travelToLocusId: "wohnzimmer",
  },
  {
    id: "wohn-tisch",
    locusId: "wohnzimmer",
    umwelt: "mensch",
    title: "Couchtisch",
    verb: "Abstellen / teilen",
    description: "Zwischen den Sitzen. Tasse, Buch, ein zweites Glas.",
    humanUse: "Den sozialen Raum halten, ohne zu arbeiten.",
    dimension: "sozial",
    lx: -0.1,
    ly: -0.1,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 14,
    salience: 0.44,
    travelToLocusId: "wohnzimmer",
  },

  // —— Haus: Treppe, Hof ——
  {
    id: "treppe-steigen",
    locusId: "treppenhaus",
    umwelt: "mensch",
    title: "Stufen",
    verb: "Steigen",
    description: "Zwischen Wohnungstür und Hof. Ein Körper tut das ohne nachzudenken.",
    humanUse: "Das Haus verlassen oder nach oben zurück.",
    dimension: "handeln",
    lx: 0,
    ly: 0.4,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 28,
    salience: 0.62,
    travelToLocusId: "treppenhaus",
    features: ["Stufe"],
    wiring: { domain: "haus", adapterId: "haus-mensch" },
  },
  {
    id: "treppe-klingel",
    locusId: "treppenhaus",
    umwelt: "mensch",
    title: "Klingeltableau",
    verb: "Drücken",
    description: "Namen, ein Knopf. Angebot nur, wenn jemand erwartet wird.",
    humanUse: "Jemanden hereinbitten, ohne die Tür offenzulassen.",
    dimension: "sozial",
    lx: 0.6,
    ly: -0.8,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 30,
    salience: 0.36,
    travelToLocusId: "treppenhaus",
    wiring: { domain: "haus", adapterId: "haus-mensch" },
  },
  {
    id: "hof-rad",
    locusId: "hof",
    umwelt: "mensch",
    title: "Fahrrad am Bügel",
    verb: "Losfahren",
    description: "Hinter der Haustür, nicht auf der Venloer.",
    humanUse: "Den Radius sprunghaft vergrößern.",
    dimension: "handeln",
    lx: 1.2,
    ly: -2.4,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 70,
    salience: 0.56,
    travelToLocusId: "hof",
  },
  {
    id: "hof-muell",
    locusId: "hof",
    umwelt: "mensch",
    title: "Mülltonnen",
    verb: "Öffnen / trennen",
    description: "Ein Alltagsangebot, kein Ausflug.",
    humanUse: "Den Haushalt nach draußen geben.",
    dimension: "handeln",
    lx: 3.2,
    ly: 1.1,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 75,
    salience: 0.34,
    travelToLocusId: "hof",
  },
  {
    id: "hof-bank",
    locusId: "hof",
    umwelt: "mensch",
    title: "Hofbank",
    verb: "Setzen",
    description: "Ein Sitz ohne Venloer. Rauchen, warten, Luft.",
    humanUse: "Draußen sein, ohne in den Kiez zu gehen.",
    dimension: "ruhen",
    lx: -1.4,
    ly: 0.6,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 72,
    salience: 0.4,
    travelToLocusId: "hof",
  },

  // —— Haus / Straße ——
  {
    id: "strasse-tuer",
    locusId: "strasse",
    title: "Haustür",
    verb: "Treten",
    description: "Treppenhaus, dann Bürgersteig.",
    humanUse: "Den Innenhorizont verlassen.",
    dimension: "handeln",
    lx: -2,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 55,
    salience: 0.58,
    travelToLocusId: "strasse",
  },
  {
    id: "strasse-brief",
    locusId: "strasse",
    title: "Briefkasten",
    verb: "Nachsehen",
    description: "Am Hauseingang, ohne weiterzugehen.",
    humanUse: "Post als Alltagsfeature der Schwelle.",
    dimension: "informieren",
    lx: -1.2,
    ly: 0.6,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 60,
    salience: 0.42,
  },
  {
    id: "strasse-rad",
    locusId: "strasse",
    title: "Fahrrad im Hof",
    verb: "Losfahren",
    description: "Anlehnbügel hinter der Haustür.",
    humanUse: "Den Radius sprunghaft vergrößern.",
    dimension: "handeln",
    lx: 3,
    ly: -4,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 70,
    salience: 0.5,
  },
  {
    id: "strasse-nachbar",
    locusId: "strasse",
    title: "Nachbarin auf der Treppe",
    verb: "Begrüßen",
    description: "Nur, wenn jemand da ist — abends wahrscheinlicher.",
    humanUse: "Soziale Nutzung der Schwelle, kein Ziel, ein Angebot.",
    dimension: "sozial",
    lx: 1,
    ly: 1.4,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 50,
    salience: 0.4,
    closedAt: ["nacht"],
  },

  // —— Kiez: Venloer, Kiosk, Halt ——
  {
    id: "venloer-gehen",
    locusId: "venloer",
    umwelt: "mensch",
    title: "Bürgersteig Venloer",
    verb: "Gehen",
    description: "Asphalt unter dem Fuß. Nicht die Route. Der Weg als Angebot.",
    humanUse: "Den Horizont der Wohnung verlassen, ohne ein Ziel zu kaufen.",
    dimension: "handeln",
    lx: 0,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 140,
    salience: 0.7,
    travelToLocusId: "venloer",
    features: ["Fuß"],
    wiring: { domain: "gehen", adapterId: "gehen-mensch" },
  },
  {
    id: "venloer-schau",
    locusId: "venloer",
    umwelt: "mensch",
    title: "Schaufenster",
    verb: "Hinsehen",
    description: "Was die Straße dem Blick gibt, ohne einzutreten.",
    humanUse: "Lage prüfen: offen, zu, wer steht.",
    dimension: "wahrnehmen",
    lx: 4,
    ly: 2,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 150,
    salience: 0.42,
    travelToLocusId: "venloer",
  },
  {
    id: "kiosk-ort",
    locusId: "kiosk",
    umwelt: "mensch",
    title: "Kiosk an der Venloer",
    verb: "Treten / kaufen",
    description: "Zweiter Bestand. Länger offen als die Bäckerei.",
    humanUse: "Wasser, Zeitung, das Kleine, wenn die Bäckerei schon zu ist.",
    dimension: "konsumieren",
    lx: 0,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 210,
    salience: 0.78,
    travelToLocusId: "kiosk",
    closedAt: ["nacht"],
    features: ["Theke", "Bestand"],
    wiring: { domain: "bestand", adapterId: "kiosk-mensch" },
    inventory: [
      { name: "Wasser", available: ["morgen", "tag", "abend"] },
      { name: "Zeitung", available: ["morgen", "tag"], note: "abends oft weg" },
      { name: "Kaugummi", available: ["morgen", "tag", "abend"] },
      { name: "Kaffee to go", available: ["morgen", "tag"] },
    ],
  },
  {
    id: "kiosk-abend",
    locusId: "kiosk",
    umwelt: "mensch",
    title: "Abendfenster",
    verb: "Klopfen / nehmen",
    description: "Später als die Bäckerei. Dieselbe Logik: was noch da ist.",
    humanUse: "Nach der Arbeit noch etwas holen, ohne in die Stadt zu fahren.",
    dimension: "konsumieren",
    lx: 0.4,
    ly: 1.1,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 4,
    salience: 0.6,
    closedAt: ["morgen", "nacht"],
  },
  {
    id: "halt-warten",
    locusId: "halt",
    umwelt: "mensch",
    title: "Wartehäuschen",
    verb: "Warten",
    description: "Bahn als Angebot. Nicht als Layer auf einer Karte.",
    humanUse: "Den Horizont springen, wenn der Fuß nicht reicht.",
    dimension: "handeln",
    lx: 0,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 320,
    salience: 0.58,
    travelToLocusId: "halt",
    features: ["Bahn"],
    wiring: { domain: "gehen", adapterId: "gehen-mensch" },
  },
  {
    id: "halt-tafel",
    locusId: "halt",
    umwelt: "mensch",
    title: "Abfahrtstafel",
    verb: "Nachsehen",
    description: "Minuten, Linie, Störung. Was jetzt fährt.",
    humanUse: "Entscheiden, ob warten sich lohnt.",
    dimension: "informieren",
    lx: 1.2,
    ly: 0.4,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 6,
    salience: 0.64,
    travelToLocusId: "halt",
    features: ["Bahn"],
    wiring: { domain: "gehen", adapterId: "gehen-mensch" },
  },

  // —— Kiez: Bäckerei mit Bestand ——
  {
    id: "baeckerei-ort",
    locusId: "baeckerei",
    title: "Bäckerei an der Venloer",
    verb: "Hinlaufen",
    description: "Erweiterter Radius. Nicht das Gebäude, sondern was ein Mensch dort tun würde.",
    humanUse: "Frühstück, Bestand prüfen, kurz unter Leute.",
    dimension: "konsumieren",
    lx: 0,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 380,
    salience: 0.94,
    travelToLocusId: "baeckerei",
    closedAt: ["nacht"],
    features: ["Theke", "Bestand", "Schlange"],
    wiring: { domain: "bestand", adapterId: "baeckerei-mensch" },
    inventory: [
      { name: "Roggenbrötchen", available: ["morgen", "tag", "abend"], note: "den ganzen Tag" },
      { name: "Körnerbrötchen", available: ["morgen", "tag"], note: "nachmittags oft leer" },
      { name: "Laugenstange", available: ["morgen", "tag", "abend"] },
      { name: "Milchbrötchen", available: ["morgen"], note: "meist vor zehn weg" },
      { name: "Franzbrötchen", available: ["morgen", "tag"] },
      { name: "Vollkorn", available: ["morgen", "tag", "abend"] },
    ],
  },
  {
    id: "baeckerei-theke",
    locusId: "baeckerei",
    title: "Theke",
    verb: "Bestellen",
    description: "Was du siehst, wenn du im Laden stehst: Glas, Zange, Preis.",
    humanUse: "Wählen aus dem, was heute wirklich da ist.",
    dimension: "konsumieren",
    lx: 0.2,
    ly: 2.2,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 4,
    salience: 0.96,
    closedAt: ["nacht"],
    umwelt: "mensch",
    wiring: { domain: "bestand", adapterId: "baeckerei-mensch" },
    inventory: [
      { name: "Roggenbrötchen", available: ["morgen", "tag", "abend"] },
      { name: "Körnerbrötchen", available: ["morgen", "tag"], note: "nachmittags oft leer" },
      { name: "Laugenstange", available: ["morgen", "tag", "abend"] },
      { name: "Milchbrötchen", available: ["morgen"], note: "meist vor zehn weg" },
      { name: "Franzbrötchen", available: ["morgen", "tag"] },
      { name: "Vollkorn", available: ["morgen", "tag", "abend"] },
    ],
  },
  {
    id: "baeckerei-kaffee",
    locusId: "baeckerei",
    title: "Kaffee zum Mitnehmen",
    verb: "Mitnehmen",
    description: "Neben der Brötchenwahl das zweite typische Feature.",
    humanUse: "Wärme für den Rückweg ins Studio.",
    dimension: "konsumieren",
    lx: 1.1,
    ly: 1.8,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 5,
    salience: 0.7,
    closedAt: ["nacht"],
  },
  {
    id: "baeckerei-schlange",
    locusId: "baeckerei",
    title: "Schlange an der Theke",
    verb: "Anstehen / warten",
    description: "Soziales Feature des Ladens, kein Produkt.",
    humanUse: "Mitwarten, hören, was andere nehmen — Teil der Nutzung.",
    dimension: "sozial",
    lx: -0.6,
    ly: 1.2,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 3,
    salience: 0.55,
    closedAt: ["abend", "nacht"],
  },
  {
    id: "baeckerei-sitz",
    locusId: "baeckerei",
    title: "Fensterbank",
    verb: "Kurz setzen",
    description: "Zwei Plätze zur Straße.",
    humanUse: "Essen, bevor man zurückgeht.",
    dimension: "ruhen",
    lx: -1.8,
    ly: -0.4,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 6,
    salience: 0.4,
    closedAt: ["nacht"],
  },

  // —— Kiez weiter ——
  {
    id: "park-bank",
    locusId: "park",
    title: "Bank im Grüngürtel",
    verb: "Setzen / gehen",
    description: "Ohne Kauf, ohne Auftrag.",
    humanUse: "Den Körper aus der Wohnung nehmen.",
    dimension: "ruhen",
    lx: 4,
    ly: -2,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 720,
    salience: 0.5,
    travelToLocusId: "park",
    closedAt: ["nacht"],
  },
  {
    id: "park-wiese",
    locusId: "park",
    title: "Wiese",
    verb: "Liegen / spielen",
    description: "Offene Fläche, Wetter abhängig.",
    humanUse: "Freizeit als räumliches Angebot, nicht als Programm.",
    dimension: "ruhen",
    lx: 12,
    ly: 8,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 740,
    salience: 0.38,
    travelToLocusId: "park",
    closedAt: ["nacht"],
  },

  // —— Stadt ——
  {
    id: "dom-treffen",
    locusId: "dom",
    title: "Domplatte",
    verb: "Ankommen / treffen",
    description: "Städtischer Treffpunkt. Weit, aber klar adressierbar.",
    humanUse: "Sich verabreden, ankommen, den Maßstab wechseln.",
    dimension: "sozial",
    lx: 0,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 2800,
    salience: 0.48,
    travelToLocusId: "dom",
    features: ["Bahn", "Treffpunkt", "Vorplatz"],
  },
  {
    id: "dom-blick",
    locusId: "dom",
    title: "Westfassade",
    verb: "Ansehen",
    description: "Wahrnehmungsangebot im großen Maßstab.",
    humanUse: "Sich orientieren, staunen, fotografieren.",
    dimension: "wahrnehmen",
    lx: 8,
    ly: 20,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 2820,
    salience: 0.42,
    travelToLocusId: "dom",
  },
];
