import type { Locus } from "./types";

export const LOCI: Locus[] = [
  {
    id: "studio",
    name: "Büro",
    kind: "Arbeitsraum",
    district: "Wohnung, Hürth",
    x: 0,
    y: 0,
    defaultFacing: 38,
    blurb:
      "Mitte des Zimmers, nicht am Rechner. Blick zur Ecke aus Fenster und Tür: Rollladen und Lichtschalter liegen im selben Gesichtsfeld — du müsstest hingehen.",
  },
  {
    id: "wohnzimmer",
    name: "Wohnzimmer",
    kind: "Aufenthalt",
    district: "Wohnung, Hürth",
    x: 8.1,
    y: 3.4,
    defaultFacing: 0,
    blurb: "Sofa, Fenster zur Straße, der soziale Innenraum der Wohnung.",
  },
  {
    id: "kueche",
    name: "Küche",
    kind: "Versorgung",
    district: "Wohnung, Hürth",
    x: 8.2,
    y: -2.8,
    defaultFacing: 180,
    blurb: "Wasser, Wärme, Vorrat. Der Raum, in dem der Körper sich wiederherstellt.",
  },
  {
    id: "bad",
    name: "Bad",
    kind: "Care",
    district: "Wohnung, Hürth",
    x: 3.5,
    y: -5.4,
    defaultFacing: 180,
    blurb: "Waschen, Spiegel, kurze Rückzüge aus dem Arbeitstag.",
  },
  {
    id: "flur",
    name: "Flur",
    kind: "Schwelle",
    district: "Wohnung, Hürth",
    x: 4.55,
    y: 0.35,
    defaultFacing: 90,
    blurb: "Verteiler der Wohnung. Von hier aus kippt der Horizont in die Nachbarräume.",
  },
  {
    id: "treppenhaus",
    name: "Treppenhaus",
    kind: "Schwelle",
    district: "Haus, Hürth",
    x: 11.4,
    y: 0.6,
    defaultFacing: 90,
    blurb: "Zwischen Wohnung und Hof. Stufen, Klingel, die Enge vor der Stadt.",
  },
  {
    id: "hof",
    name: "Hof",
    kind: "Frei",
    district: "Haus, Hürth",
    x: 16.2,
    y: -7.4,
    defaultFacing: 180,
    blurb: "Hinter der Haustür. Fahrrad, Müll, ein Stück Himmel ohne Straße.",
  },
  {
    id: "strasse",
    name: "Haustür",
    kind: "Straße",
    district: "Hürth",
    x: 18,
    y: 2,
    defaultFacing: 95,
    blurb: "Schwelle zur Stadt. Briefkasten, Nachbar, der erste Atem draußen.",
  },
  {
    id: "venloer",
    name: "Venloer",
    kind: "Straße",
    district: "Ehrenfeld, Köln",
    x: 7800,
    y: 4100,
    defaultFacing: 95,
    blurb: "Köln, nicht die Straße vor der Tür. Bahn, dann Fuß.",
  },
  {
    id: "kiosk",
    name: "Kiosk",
    kind: "Laden",
    district: "Hürth",
    x: 145,
    y: 48,
    defaultFacing: 10,
    blurb: "Zweiter Bestand. Wasser, Zeitung, was nach der Bäckerei noch offen ist.",
  },
  {
    id: "halt",
    name: "Haltestelle",
    kind: "Bahn",
    district: "Hürth",
    x: 260,
    y: 95,
    defaultFacing: 20,
    blurb: "Bahn als Angebot, nicht als Layer. Warten, einsteigen, den Horizont springen.",
  },
  {
    id: "baeckerei",
    name: "Bäckerei",
    kind: "Laden",
    district: "Hürth",
    x: 420,
    y: 165,
    defaultFacing: 0,
    blurb:
      "Laufweite. Bestand, der sich über den Tag leert. Kein Ladenname.",
  },
  {
    id: "park",
    name: "Park",
    kind: "Freiraum",
    district: "Hürth",
    x: 780,
    y: -240,
    defaultFacing: 140,
    blurb: "Gehen ohne Auftrag. Bänke, Wiese, der Kiez als Atemraum.",
  },
  {
    id: "dom",
    name: "Domplatte",
    kind: "Ort",
    district: "Altstadt-Nord",
    x: 3400,
    y: 2100,
    defaultFacing: 200,
    blurb: "Städtischer Pol. Ankunft, Treffen, der große Maßstab Kölns.",
  },
];

export function locusById(id: string): Locus {
  const found = LOCI.find((l) => l.id === id);
  if (!found) throw new Error(`Unknown locus ${id}`);
  return found;
}
