import type { Affordance, Umwelt } from "./types";

export const UMWELTEN: Umwelt[] = [
  {
    id: "mensch",
    label: "Mensch",
    short: "Leib",
    hint: "Was ein Körper hier wirklich nutzen würde.",
    studioFacing: 38,
  },
  {
    id: "entwickler",
    label: "Entwickler",
    short: "Anschluss",
    hint: "Was sich anbinden, messen, trainieren, schicken lässt.",
    studioFacing: 270,
  },
  {
    id: "roboter",
    label: "Roboter",
    short: "Körper²",
    hint: "Boden, Maß, Strom, Masse, was ein Apparat hier tun kann.",
    studioFacing: 90,
  },
];

export function umweltOf(id: Umwelt["id"]): Umwelt {
  const found = UMWELTEN.find((u) => u.id === id);
  if (!found) throw new Error(`Unknown umwelt ${id}`);
  return found;
}

/** Offers that exist only for a machine or a developer in the same places. */
export const MACHINE_AFFORDANCES: Affordance[] = [
  // —— Entwickler, Studio ——
  {
    id: "dev-rechner",
    locusId: "studio",
    umwelt: "entwickler",
    title: "Rechner am Schreibtisch",
    verb: "Aufwachen / anbinden",
    description: "Westwand. In dieser Umwelt das erste Angebot, nicht das letzte.",
    humanUse: "Hier beginnt die Welt als Schnittstelle: Prozess, Datei, Port.",
    dimension: "schaffen",
    lx: -3.15,
    ly: 0.35,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 6,
    salience: 0.99,
    features: ["Shell", "Repo", "Modell"],
    wiring: { domain: "modell", adapterId: "modell-entwickler" },
  },
  {
    id: "dev-terminal",
    locusId: "studio",
    umwelt: "entwickler",
    title: "Offenes Terminal",
    verb: "Lesen / schicken",
    description: "Armlänge, sobald man sitzt. Logs, Tokens, Fehler.",
    humanUse: "Der Bestand ist hier nicht Brötchen, sondern Kontext und Ausgabe.",
    dimension: "informieren",
    lx: -3.0,
    ly: 0.55,
    visibleStanding: true,
    requiresWalk: false,
    walkSeconds: 2,
    salience: 0.94,
    inventory: [
      { name: "Kontext frei", available: ["morgen", "tag", "abend", "nacht"] },
      { name: "GPU warm", available: ["morgen", "tag", "abend"] },
      { name: "Rate-Limit", available: ["tag"], note: "nachmittags eng" },
    ],
  },
  {
    id: "dev-midi",
    locusId: "studio",
    umwelt: "entwickler",
    title: "MIDI über USB",
    verb: "Mappen",
    description: "Dieselbe Tastatur. Für dich Klang, für die Maschine ein Strom von Zahlen.",
    humanUse: "Anschluss, nicht Instrument.",
    dimension: "schaffen",
    lx: 0.95,
    ly: -0.35,
    visibleStanding: true,
    requiresWalk: false,
    walkSeconds: 3,
    salience: 0.72,
  },
  {
    id: "dev-netz",
    locusId: "studio",
    umwelt: "entwickler",
    title: "Netzwerkdose / Funk",
    verb: "Route prüfen",
    description: "Was den Raum an Server bindet. Ohne das fällt die Umwelt zusammen.",
    humanUse: "Erreichbarkeit als Bedingung, nicht als Komfort.",
    dimension: "handeln",
    lx: -3.6,
    ly: -1.4,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 5,
    salience: 0.8,
  },
  {
    id: "dev-leiste",
    locusId: "studio",
    umwelt: "entwickler",
    title: "Steckdosenleiste",
    verb: "Last halten",
    description: "Unter dem Tisch. Watt, nicht Wärme für die Hände.",
    humanUse: "Strombudget der Karten und Platten.",
    dimension: "handeln",
    lx: -3.4,
    ly: -0.6,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 6,
    salience: 0.58,
  },
  {
    id: "dev-fenster-licht",
    locusId: "studio",
    umwelt: "entwickler",
    title: "Tageslicht auf dem Schirm",
    verb: "Blende / nicht sehen",
    description: "Derselbe Rollladen. Hier stört er Pixel, nicht Stimmung.",
    humanUse: "Kontrast für lange Sessions.",
    dimension: "wahrnehmen",
    lx: 0.35,
    ly: 3.85,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 7,
    salience: 0.5,
  },
  {
    id: "dev-kaffee",
    locusId: "kueche",
    umwelt: "entwickler",
    title: "Siebträger als Takt",
    verb: "Unterbrechen",
    description: "Nicht Hunger. Der Schnitt zwischen zwei Läufen.",
    humanUse: "Pause, die den Prozess nicht killt.",
    dimension: "ruhen",
    lx: 0.2,
    ly: 1.4,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 18,
    salience: 0.55,
    travelToLocusId: "kueche",
    closedAt: ["nacht"],
  },
  {
    id: "dev-baeckerei",
    locusId: "baeckerei",
    umwelt: "entwickler",
    title: "Fensterplatz mit Dose",
    verb: "Setzen / senden",
    description: "Dieselbe Bäckerei. Angebot: Strom, Funk, nicht der Bestand an Milchbrötchen.",
    humanUse: "Ausweichplatz, wenn das Büro zu eng wird.",
    dimension: "schaffen",
    lx: -1.8,
    ly: -0.4,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 380,
    salience: 0.88,
    travelToLocusId: "baeckerei",
    closedAt: ["nacht"],
    features: ["WLAN", "Steckdose", "Lärm"],
  },
  {
    id: "dev-cloud",
    locusId: "dom",
    umwelt: "entwickler",
    title: "Rechenort FRA",
    verb: "Schicken / holen",
    description: "Der städtische Horizont ist hier ein Rechenzentrum, nicht die Fassade.",
    humanUse: "Nähe als Latenz, nicht als Treffpunkt.",
    dimension: "informieren",
    lx: 0,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 2800,
    salience: 0.62,
    travelToLocusId: "dom",
    features: ["Region", "Tick"],
  },

  // —— Roboter, Studio ——
  {
    id: "bot-boden",
    locusId: "studio",
    umwelt: "roboter",
    title: "Freie Bodenfläche",
    verb: "Verfahren",
    description: "Was zwischen den Möbeln noch tragfähig und leer ist.",
    humanUse: "Fortbewegung, nicht Wohnen.",
    dimension: "handeln",
    lx: 0.2,
    ly: 0.1,
    visibleStanding: true,
    requiresWalk: false,
    walkSeconds: 2,
    salience: 0.96,
    features: ["Reibung", "Kabel"],
    wiring: { domain: "apparat", adapterId: "apparat-roboter" },
  },
  {
    id: "bot-tuer",
    locusId: "studio",
    umwelt: "roboter",
    title: "Türlichtmaß",
    verb: "Durchqueren",
    description: "Dieselbe Tür. Angebot: Breite, Schwelle, Kraft am Blatt.",
    humanUse: "Passieren oder steckenbleiben.",
    dimension: "handeln",
    lx: 3.5,
    ly: 0.75,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 6,
    salience: 0.95,
    travelToLocusId: "flur",
    features: ["72 cm", "Schwelle"],
  },
  {
    id: "bot-dose",
    locusId: "studio",
    umwelt: "roboter",
    title: "Steckdose in Reichweite",
    verb: "Andocken",
    description: "Unter dem Fenster. Für dich Heizung, für den Apparat Restlaufzeit.",
    humanUse: "Energie als Horizont.",
    dimension: "ruhen",
    lx: 1.35,
    ly: 3.7,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 8,
    salience: 0.9,
    wiring: { domain: "haus", adapterId: "haus-roboter" },
  },
  {
    id: "bot-glas",
    locusId: "studio",
    umwelt: "roboter",
    title: "Glasfläche Fenster",
    verb: "Meiden / belichten",
    description: "Kein Blick auf Höfe. Hindernis, Spiegelung, Lichtquelle für die Kamera.",
    humanUse: "Wahrnehmung als Sensor, nicht als Stimmung.",
    dimension: "wahrnehmen",
    lx: 0.15,
    ly: 4.0,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 6,
    salience: 0.7,
  },
  {
    id: "bot-gitarre",
    locusId: "studio",
    umwelt: "roboter",
    title: "Masse an der Wand",
    verb: "Nicht greifen",
    description: "Dieselbe Gitarre. Kein Klang. Ein Gegenstand mit Gewicht und Saiten.",
    humanUse: "Kollision, Last, kein Instrument.",
    dimension: "handeln",
    lx: -0.35,
    ly: -3.15,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 6,
    salience: 0.42,
  },
  {
    id: "bot-schalter",
    locusId: "studio",
    umwelt: "roboter",
    title: "Wippe in 1,10 m",
    verb: "Drücken, wenn Arm reicht",
    description: "Derselbe Lichtschalter. Angebot nur, wenn der Effektor so hoch kommt.",
    humanUse: "Höhe und Kraft, nicht Gewohnheit.",
    dimension: "handeln",
    lx: 3.35,
    ly: -0.15,
    visibleStanding: true,
    requiresWalk: true,
    walkSeconds: 6,
    salience: 0.74,
  },
  {
    id: "bot-flur",
    locusId: "flur",
    umwelt: "roboter",
    title: "Engstelle Flur",
    verb: "Wenden / nicht wenden",
    description: "Verteiler für dich. Für den Apparat ein Korridor mit Wendekreis.",
    humanUse: "Geometrie vor Absicht.",
    dimension: "handeln",
    lx: 0,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 8,
    salience: 0.68,
    travelToLocusId: "flur",
  },
  {
    id: "bot-strasse",
    locusId: "strasse",
    umwelt: "roboter",
    title: "Bordsteinkante",
    verb: "Steigen / scheitern",
    description: "Die Schwelle zur Stadt als Höhe, nicht als Freiheit.",
    humanUse: "Ein Zentimeter entscheidet, ob der Horizont aufgeht.",
    dimension: "handeln",
    lx: -2,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 55,
    salience: 0.8,
    travelToLocusId: "strasse",
  },
  {
    id: "bot-baeckerei",
    locusId: "baeckerei",
    umwelt: "roboter",
    title: "Ladentür und Dichte",
    verb: "Halten / nicht eintreten",
    description: "Nicht der Bestand. Stufe, Knauf, Menschenmenge, nasser Boden.",
    humanUse: "Betreten als Risiko, nicht als Frühstück.",
    dimension: "handeln",
    lx: 0,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 380,
    salience: 0.86,
    travelToLocusId: "baeckerei",
    closedAt: ["nacht"],
    features: ["Stufe", "Knauf", "Gedränge"],
    wiring: { domain: "bestand", adapterId: "baeckerei-roboter" },
  },

  // —— Entwickler, Wohnung und Haus ——
  {
    id: "dev-kueche-zaehler",
    locusId: "kueche",
    umwelt: "entwickler",
    title: "Steckdose hinter der Zeile",
    verb: "Last lesen",
    description: "Dieselbe Küche. Angebot: Stromkreis, nicht Hunger.",
    humanUse: "Messpunkt, kein Herd.",
    dimension: "informieren",
    lx: -0.4,
    ly: 1.1,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 20,
    salience: 0.58,
    travelToLocusId: "kueche",
    wiring: { domain: "haus", adapterId: "haus-entwickler" },
  },
  {
    id: "dev-bad-nasse",
    locusId: "bad",
    umwelt: "entwickler",
    title: "Feuchtraum-Kreis",
    verb: "Nicht legen",
    description: "FI, IP44. Der Raum als Grenze für Hardware.",
    humanUse: "Verkabelung stoppt hier anders als im Büro.",
    dimension: "handeln",
    lx: 0.2,
    ly: 0.5,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 16,
    salience: 0.5,
    travelToLocusId: "bad",
    wiring: { domain: "haus", adapterId: "haus-entwickler" },
  },
  {
    id: "dev-wohn-cast",
    locusId: "wohnzimmer",
    umwelt: "entwickler",
    title: "Bildschirm am Netz",
    verb: "Senden",
    description: "Dasselbe Sofa. Hier ein Endpunkt, kein Sitz.",
    humanUse: "Ausgabe, nicht Ausruhen.",
    dimension: "schaffen",
    lx: 1.2,
    ly: 2.0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 16,
    salience: 0.54,
    travelToLocusId: "wohnzimmer",
  },
  {
    id: "dev-klingel",
    locusId: "treppenhaus",
    umwelt: "entwickler",
    title: "Bus der Klingel",
    verb: "Event lesen",
    description: "Dieselbe Klingel. Angebot: Impuls, Türöffner-Relais.",
    humanUse: "Ein Event, keine Begrüßung.",
    dimension: "informieren",
    lx: 0.6,
    ly: -0.8,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 30,
    salience: 0.66,
    travelToLocusId: "treppenhaus",
    wiring: { domain: "haus", adapterId: "haus-entwickler" },
  },
  {
    id: "dev-hof-funk",
    locusId: "hof",
    umwelt: "entwickler",
    title: "Funkloch hinterm Haus",
    verb: "Messen",
    description: "Dieselbe Hofmauer. RSSI, nicht Himmel.",
    humanUse: "Reichweite prüfen, bevor ein Sensor draußen bleibt.",
    dimension: "informieren",
    lx: 0,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 70,
    salience: 0.48,
    travelToLocusId: "hof",
  },
  {
    id: "dev-venloer-zelle",
    locusId: "venloer",
    umwelt: "entwickler",
    title: "Mobilfunkzelle",
    verb: "Handover / pingen",
    description: "Dieselbe Straße. Angebot: Träger, nicht Bürgersteig.",
    humanUse: "Latenz und Dichte, kein Spaziergang.",
    dimension: "informieren",
    lx: 0,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 5400,
    salience: 0.6,
    travelToLocusId: "venloer",
    wiring: { domain: "gehen", adapterId: "gehen-entwickler" },
  },
  {
    id: "dev-kiosk-kasse",
    locusId: "kiosk",
    umwelt: "entwickler",
    title: "Kassenfeed",
    verb: "Lesen",
    description: "Zweiter Bestand als Daten: SKU, Rest, Öffnung.",
    humanUse: "Feed, nicht Durst.",
    dimension: "informieren",
    lx: 0,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 210,
    salience: 0.72,
    travelToLocusId: "kiosk",
    closedAt: ["nacht"],
    wiring: { domain: "bestand", adapterId: "kiosk-entwickler" },
    inventory: [
      { name: "Wasser · SKU", available: ["morgen", "tag", "abend"] },
      { name: "Zeitung · SKU", available: ["morgen", "tag"] },
    ],
  },
  {
    id: "dev-halt-gtfs",
    locusId: "halt",
    umwelt: "entwickler",
    title: "Abfahrtsfeed",
    verb: "Holen",
    description: "Dieselbe Haltestelle. JSON, nicht Warten.",
    humanUse: "Soll-Ist, Störungscode.",
    dimension: "informieren",
    lx: 1.2,
    ly: 0.4,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 320,
    salience: 0.74,
    travelToLocusId: "halt",
    features: ["Bahn"],
    wiring: { domain: "gehen", adapterId: "gehen-entwickler" },
  },
  {
    id: "dev-baeckerei-bestand",
    locusId: "baeckerei",
    umwelt: "entwickler",
    title: "Restmenge Theke",
    verb: "Zählen",
    description: "Nicht der Geschmack. Stückzahl, Uhrzeit, Leerung.",
    humanUse: "Bestand als Zeitreihe.",
    dimension: "informieren",
    lx: 0.2,
    ly: 2.2,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 380,
    salience: 0.9,
    travelToLocusId: "baeckerei",
    closedAt: ["nacht"],
    wiring: { domain: "bestand", adapterId: "baeckerei-entwickler" },
    inventory: [
      { name: "Roggenbrötchen", available: ["morgen", "tag", "abend"] },
      { name: "Milchbrötchen", available: ["morgen"], note: "meist vor zehn weg" },
      { name: "Körnerbrötchen", available: ["morgen", "tag"] },
    ],
  },

  // —— Roboter, Wohnung und Haus ——
  {
    id: "bot-kueche-nasse",
    locusId: "kueche",
    umwelt: "roboter",
    title: "Nasser Fliesenboden",
    verb: "Meiden / langsam",
    description: "Dieselbe Küche. Reibung, Pfütze, nicht Kochen.",
    humanUse: "Traktion, kein Hunger.",
    dimension: "handeln",
    lx: 0.5,
    ly: 0.4,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 20,
    salience: 0.7,
    travelToLocusId: "kueche",
    features: ["glatt", "nass"],
    wiring: { domain: "apparat", adapterId: "apparat-roboter" },
  },
  {
    id: "bot-bad-schwelle",
    locusId: "bad",
    umwelt: "roboter",
    title: "Duschkante",
    verb: "Nicht überfahren",
    description: "Dieselbe Dusche. Höhe, Nässe, Glas.",
    humanUse: "Grenze, kein Waschen.",
    dimension: "handeln",
    lx: -1.2,
    ly: -1.2,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 18,
    salience: 0.66,
    travelToLocusId: "bad",
    features: ["Schwelle", "Glas"],
    wiring: { domain: "apparat", adapterId: "apparat-roboter" },
  },
  {
    id: "bot-wohn-teppich",
    locusId: "wohnzimmer",
    umwelt: "roboter",
    title: "Teppichkante",
    verb: "Stecken / steigen",
    description: "Dasselbe Sofa. Für den Apparat ein Höhenwechsel am Boden.",
    humanUse: "Befahrbarkeit, kein Sitzen.",
    dimension: "handeln",
    lx: -0.4,
    ly: -0.6,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 14,
    salience: 0.62,
    travelToLocusId: "wohnzimmer",
    features: ["blockiert"],
    wiring: { domain: "apparat", adapterId: "apparat-roboter" },
  },
  {
    id: "bot-treppe",
    locusId: "treppenhaus",
    umwelt: "roboter",
    title: "Steigung der Treppe",
    verb: "Scheitern / heben",
    description: "Dieselben Stufen. Für die meisten Apparate ein Ende.",
    humanUse: "Kein Anthropomorphismus. Eine Treppe ist keine Einladung.",
    dimension: "handeln",
    lx: 0,
    ly: 0.4,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 28,
    salience: 0.92,
    travelToLocusId: "treppenhaus",
    features: ["Stufe", "nicht befahrbar"],
    wiring: { domain: "apparat", adapterId: "apparat-roboter" },
  },
  {
    id: "bot-hof-kies",
    locusId: "hof",
    umwelt: "roboter",
    title: "Hofbelag",
    verb: "Verfahren / rutschen",
    description: "Kies oder Platte. Reibung, Gitter, Pfütze.",
    humanUse: "Bodenklasse, kein Aufenthalt.",
    dimension: "handeln",
    lx: 0,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 70,
    salience: 0.7,
    travelToLocusId: "hof",
    features: ["befahrbar"],
    wiring: { domain: "apparat", adapterId: "apparat-roboter" },
  },
  {
    id: "bot-venloer-bord",
    locusId: "venloer",
    umwelt: "roboter",
    title: "Bordstein und Dichte",
    verb: "Halten / nicht queren",
    description: "Dieselbe Straße in Ehrenfeld. Höhe, Fußgänger, Glasfront.",
    humanUse: "Sicherheit vor Absicht.",
    dimension: "handeln",
    lx: 0,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 5400,
    salience: 0.84,
    travelToLocusId: "venloer",
    features: ["Bordstein", "Gedränge"],
    wiring: { domain: "gehen", adapterId: "gehen-roboter" },
  },
  {
    id: "bot-kiosk-knauf",
    locusId: "kiosk",
    umwelt: "roboter",
    title: "Knauf und Schwelle",
    verb: "Nicht eintreten",
    description: "Zweiter Laden. Dieselbe Logik wie die Bäckerei: Stufe, Enge.",
    humanUse: "Geometrie, nicht Durst.",
    dimension: "handeln",
    lx: 0,
    ly: 0,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 210,
    salience: 0.8,
    travelToLocusId: "kiosk",
    closedAt: ["nacht"],
    features: ["Knauf", "Stufe"],
    wiring: { domain: "bestand", adapterId: "kiosk-roboter" },
  },
  {
    id: "bot-halt-luecke",
    locusId: "halt",
    umwelt: "roboter",
    title: "Lücke zur Tür",
    verb: "Nicht überbrücken",
    description: "Bahnsteigkante. Spalt, Höhe, bewegte Masse.",
    humanUse: "Ein Halt ist kein Ziel, wenn der Spalt zu groß ist.",
    dimension: "handeln",
    lx: 2.4,
    ly: 0.2,
    visibleStanding: false,
    requiresWalk: true,
    walkSeconds: 330,
    salience: 0.88,
    travelToLocusId: "halt",
    features: ["Spalt", "Bahn"],
    wiring: { domain: "gehen", adapterId: "gehen-roboter" },
  },
];
