/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeldRouteImport } from './routes/feld'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModellRouteImport } from './routes/modell'
import { Route as SchnittRouteImport } from './routes/schnitt'
import { Route as MoeglichkeitensystemIndexRouteImport } from './routes/moeglichkeitensystem/index'
import { Route as MoeglichkeitensystemFeldRouteImport } from './routes/moeglichkeitensystem/feld'
import { Route as MoeglichkeitensystemSchnittRouteImport } from './routes/moeglichkeitensystem/schnitt'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeldRoute = FeldRouteImport.update({
  id: '/feld',
  path: '/feld',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModellRoute = ModellRouteImport.update({
  id: '/modell',
  path: '/modell',
  getParentRoute: () => rootRouteImport,
} as any)
const SchnittRoute = SchnittRouteImport.update({
  id: '/schnitt',
  path: '/schnitt',
  getParentRoute: () => rootRouteImport,
} as any)
const MoeglichkeitensystemIndexRoute =
  MoeglichkeitensystemIndexRouteImport.update({
    id: '/moeglichkeitensystem/',
    path: '/moeglichkeitensystem/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MoeglichkeitensystemFeldRoute =
  MoeglichkeitensystemFeldRouteImport.update({
    id: '/moeglichkeitensystem/feld',
    path: '/moeglichkeitensystem/feld',
    getParentRoute: () => rootRouteImport,
  } as any)
const MoeglichkeitensystemSchnittRoute =
  MoeglichkeitensystemSchnittRouteImport.update({
    id: '/moeglichkeitensystem/schnitt',
    path: '/moeglichkeitensystem/schnitt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feld': typeof FeldRoute
  '/login': typeof LoginRoute
  '/modell': typeof ModellRoute
  '/schnitt': typeof SchnittRoute
  '/moeglichkeitensystem/feld': typeof MoeglichkeitensystemFeldRoute
  '/moeglichkeitensystem/schnitt': typeof MoeglichkeitensystemSchnittRoute
  '/moeglichkeitensystem/': typeof MoeglichkeitensystemIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feld': typeof FeldRoute
  '/login': typeof LoginRoute
  '/modell': typeof ModellRoute
  '/schnitt': typeof SchnittRoute
  '/moeglichkeitensystem/feld': typeof MoeglichkeitensystemFeldRoute
  '/moeglichkeitensystem/schnitt': typeof MoeglichkeitensystemSchnittRoute
  '/moeglichkeitensystem': typeof MoeglichkeitensystemIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feld': typeof FeldRoute
  '/login': typeof LoginRoute
  '/modell': typeof ModellRoute
  '/schnitt': typeof SchnittRoute
  '/moeglichkeitensystem/feld': typeof MoeglichkeitensystemFeldRoute
  '/moeglichkeitensystem/schnitt': typeof MoeglichkeitensystemSchnittRoute
  '/moeglichkeitensystem/': typeof MoeglichkeitensystemIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feld'
    | '/login'
    | '/modell'
    | '/schnitt'
    | '/moeglichkeitensystem/feld'
    | '/moeglichkeitensystem/schnitt'
    | '/moeglichkeitensystem/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feld'
    | '/login'
    | '/modell'
    | '/schnitt'
    | '/moeglichkeitensystem/feld'
    | '/moeglichkeitensystem/schnitt'
    | '/moeglichkeitensystem'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/feld'
    | '/login'
    | '/modell'
    | '/schnitt'
    | '/moeglichkeitensystem/feld'
    | '/moeglichkeitensystem/schnitt'
    | '/moeglichkeitensystem/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeldRoute: typeof FeldRoute
  LoginRoute: typeof LoginRoute
  ModellRoute: typeof ModellRoute
  SchnittRoute: typeof SchnittRoute
  MoeglichkeitensystemFeldRoute: typeof MoeglichkeitensystemFeldRoute
  MoeglichkeitensystemSchnittRoute: typeof MoeglichkeitensystemSchnittRoute
  MoeglichkeitensystemIndexRoute: typeof MoeglichkeitensystemIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feld': {
      id: '/feld'
      path: '/feld'
      fullPath: '/feld'
      preLoaderRoute: typeof FeldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modell': {
      id: '/modell'
      path: '/modell'
      fullPath: '/modell'
      preLoaderRoute: typeof ModellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schnitt': {
      id: '/schnitt'
      path: '/schnitt'
      fullPath: '/schnitt'
      preLoaderRoute: typeof SchnittRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moeglichkeitensystem/': {
      id: '/moeglichkeitensystem/'
      path: '/moeglichkeitensystem'
      fullPath: '/moeglichkeitensystem/'
      preLoaderRoute: typeof MoeglichkeitensystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moeglichkeitensystem/feld': {
      id: '/moeglichkeitensystem/feld'
      path: '/moeglichkeitensystem/feld'
      fullPath: '/moeglichkeitensystem/feld'
      preLoaderRoute: typeof MoeglichkeitensystemFeldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moeglichkeitensystem/schnitt': {
      id: '/moeglichkeitensystem/schnitt'
      path: '/moeglichkeitensystem/schnitt'
      fullPath: '/moeglichkeitensystem/schnitt'
      preLoaderRoute: typeof MoeglichkeitensystemSchnittRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeldRoute: FeldRoute,
  LoginRoute: LoginRoute,
  ModellRoute: ModellRoute,
  SchnittRoute: SchnittRoute,
  MoeglichkeitensystemFeldRoute: MoeglichkeitensystemFeldRoute,
  MoeglichkeitensystemSchnittRoute: MoeglichkeitensystemSchnittRoute,
  MoeglichkeitensystemIndexRoute: MoeglichkeitensystemIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
